name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Update env.js with secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "window.env = {
            FIREBASE_API_KEY: 'AIzaSyDtQVSOLb56_QvYQhRHRF4Xan1xpEu9aas',
            FIREBASE_AUTH_DOMAIN: 'new-year-2025-7cdc8.firebaseapp.com',
            FIREBASE_PROJECT_ID: 'new-year-2025-7cdc8',
            FIREBASE_STORAGE_BUCKET: 'new-year-2025-7cdc8.firebasestorage.app',
            FIREBASE_SENDER_ID: '1021442594880',
            FIREBASE_APP_ID: '1:1021442594880:web:38d0db3d0eeb2f0f7aa7a5',
            FIREBASE_MEASUREMENT_ID: 'G-NMDTX9RED6',
            OPENAI_API_KEY: '${OPENAI_API_KEY}'
          };" > web/env.js
      - run: flutter pub get
      - run: flutter build web --release --web-renderer canvaskit 